# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2023, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
# 
# Translators:
# tomo, 2019
# Takeshi Nakazato, 2022
# 
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.7\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2023-06-02 14:49+0000\n"
"PO-Revision-Date: 2019-09-01 03:15+0000\n"
"Last-Translator: Takeshi Nakazato, 2022\n"
"Language-Team: Japanese (https://app.transifex.com/python-doc/teams/5390/ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:7
msgid "Developing with asyncio"
msgstr "asyncio での開発"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:9
msgid ""
"Asynchronous programming is different from classic \"sequential\" "
"programming."
msgstr "非同期プログラミングは伝統的な \"同期的\" プログラミングとは異なります。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:12
msgid ""
"This page lists common mistakes and traps and explains how to avoid them."
msgstr "このページはよくある間違いや落とし穴を列挙し、それらを回避する方法を説明します。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:19
msgid "Debug Mode"
msgstr "デバッグモード"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:21
msgid ""
"By default asyncio runs in production mode.  In order to ease the "
"development asyncio has a *debug mode*."
msgstr ""
"asyncio はデフォルトで本運用モードで実行されます。いっぽう、開発を容易にするために asyncio は \"デバッグモード\" を持っています。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:24
msgid "There are several ways to enable asyncio debug mode:"
msgstr "asyncio のデバッグモードを有効化する方法はいくつかあります:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:26
msgid ""
"Setting the :envvar:`PYTHONASYNCIODEBUG` environment variable to ``1``."
msgstr ":envvar:`PYTHONASYNCIODEBUG` 環境変数の値を ``1`` に設定する。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:28
msgid "Using the :option:`-X` ``dev`` Python command line option."
msgstr ""

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:30
msgid "Passing ``debug=True`` to :func:`asyncio.run`."
msgstr ":func:`asyncio.run` 実行時に ``debug=True`` を設定する。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:32
msgid "Calling :meth:`loop.set_debug`."
msgstr ":meth:`loop.set_debug` を呼び出す。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:34
msgid "In addition to enabling the debug mode, consider also:"
msgstr "デバッグモードを有効化することに加え、以下も検討してください:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:36
msgid ""
"setting the log level of the :ref:`asyncio logger <asyncio-logger>` to "
":py:data:`logging.DEBUG`, for example the following snippet of code can be "
"run at startup of the application::"
msgstr ""
":ref:`asyncio ロガー <asyncio-logger>` のログレベルを :py:data:`logging.DEBUG` "
"に設定します。例えばアプリケーションの起動時に以下を実行します::"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:42
msgid ""
"configuring the :mod:`warnings` module to display :exc:`ResourceWarning` "
"warnings.  One way of doing that is by using the :option:`-W` ``default`` "
"command line option."
msgstr ""
":mod:`warnings` モジュールが :exc:`ResourceWarning` 警告を表示するように設定します。やり方のひとつは "
":option:`-W` ``default`` コマンドラインオプションを使うことです。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:47
msgid "When the debug mode is enabled:"
msgstr "デバッグモードが有効化されたときの動作:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:49
msgid ""
"asyncio checks for :ref:`coroutines that were not awaited <asyncio-"
"coroutine-not-scheduled>` and logs them; this mitigates the \"forgotten "
"await\" pitfall."
msgstr ""
"asyncio は :ref:`待ち受け処理 (await) を伴わないコルーチン <asyncio-coroutine-not-scheduled>`"
" がないかをチェックし、それらを記録します; これにより \"待ち受け忘れ\" の落とし穴にはまる可能性を軽減します。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:53
msgid ""
"Many non-threadsafe asyncio APIs (such as :meth:`loop.call_soon` and "
":meth:`loop.call_at` methods) raise an exception if they are called from a "
"wrong thread."
msgstr ""
"スレッドセーフでない asyncio APIs の多く (:meth:`loop.call_soon` や :meth:`loop.call_at` "
"など) は、誤ったスレッドから呼び出されたときに例外を送出します。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:57
msgid ""
"The execution time of the I/O selector is logged if it takes too long to "
"perform an I/O operation."
msgstr "I/O セレクタが I/O 処理を実行する時間が長すぎる場合、その実行時間が記録されます。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:60
msgid ""
"Callbacks taking longer than 100ms are logged.  The "
":attr:`loop.slow_callback_duration` attribute can be used to set the minimum"
" execution duration in seconds that is considered \"slow\"."
msgstr ""
"実行時間が100ミリ秒を超えるコールバックは記録されます。 \"遅い\" の判断基準となる実行時間の最小値は "
":attr:`loop.slow_callback_duration` 属性で設定できます。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:68
msgid "Concurrency and Multithreading"
msgstr "並行処理とマルチスレッド処理"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:70
msgid ""
"An event loop runs in a thread (typically the main thread) and executes all "
"callbacks and Tasks in its thread.  While a Task is running in the event "
"loop, no other Tasks can run in the same thread.  When a Task executes an "
"``await`` expression, the running Task gets suspended, and the event loop "
"executes the next Task."
msgstr ""
"イベントループはスレッド（典型的にはメインスレッド）内で動作し、すべてのコールバックとタスクをそのスレッド内で実行します。ひとつのタスクがイベントループ内で実行される間、他のタスクを同じスレッド内で実行することはできません。タスクが"
" ``await`` 式を実行すると、実行中のタスクはサスペンドされ、イベントループは次のタスクを実行します。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:76
msgid ""
"To schedule a callback from a different OS thread, the "
":meth:`loop.call_soon_threadsafe` method should be used. Example::"
msgstr ""

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:81
msgid ""
"Almost all asyncio objects are not thread safe, which is typically not a "
"problem unless there is code that works with them from outside of a Task or "
"a callback.  If there's a need for such code to call a low-level asyncio "
"API, the :meth:`loop.call_soon_threadsafe` method should be used, e.g.::"
msgstr ""
"ほぼ全ての非同期オブジェクトはスレッドセーフではありませんが、タスクやコールバックの外側で非同期オブジェクトを使うコードが存在しない限り、それが問題にはなることはほとんどありません。もしそのような目的で低レベルの"
" asyncio API を呼び出すようなコードを書く必要がある場合、 :meth:`loop.call_soon_threadsafe` "
"メソッドを使ってください。例: "

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:89
msgid ""
"To schedule a coroutine object from a different OS thread, the "
":func:`run_coroutine_threadsafe` function should be used. It returns a "
":class:`concurrent.futures.Future` to access the result::"
msgstr ""
"別の OS スレッドからコルーチンオブジェクトをスケジュールする場合は、 :func:`run_coroutine_threadsafe` "
"メソッドを使ってください。 :func:`run_coroutine_threadsafe` は結果にアクセスするための "
":class:`concurrent.futures.Future`  オブジェクトを返します:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:102
msgid ""
"To handle signals and to execute subprocesses, the event loop must be run in"
" the main thread."
msgstr "シグナルの処理やサブプロセスの実行を行うには、イベントループはメインスレッド内で実行しなければなりません。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:105
msgid ""
"The :meth:`loop.run_in_executor` method can be used with a "
":class:`concurrent.futures.ThreadPoolExecutor` to execute blocking code in a"
" different OS thread without blocking the OS thread that the event loop runs"
" in."
msgstr ""
"The :meth:`loop.run_in_executor` メソッドを "
":class:`concurrent.futures.ThreadPoolExecutor` とともに使用することで、イベントループの OS "
"スレッドをブロックすることなく、別の OS スレッド内でブロッキングコードを実行することができます。 "

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:114
msgid "Running Blocking Code"
msgstr "ブロッキングコードの実行"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:116
msgid ""
"Blocking (CPU-bound) code should not be called directly.  For example, if a "
"function performs a CPU-intensive calculation for 1 second, all concurrent "
"asyncio Tasks and IO operations would be delayed by 1 second."
msgstr ""
"ブロッキングコード (CPU バウンドなコード) を直接呼び出すべきではありません。たとえば、 CPU "
"負荷の高い関数を1秒実行したとすると、並行に処理されている全ての非同期タスクと I/O 処理は1秒遅れる可能性があります。 "

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:121
msgid ""
"An executor can be used to run a task in a different thread or even in a "
"different process to avoid blocking the OS thread with the event loop.  See "
"the :meth:`loop.run_in_executor` method for more details."
msgstr ""
"エグゼキューターを使用することにより、イベントループの OS "
"スレッドをブロックすることなく、別のスレッドや別のプロセス上でタスクを実行することができます。詳しくは "
":meth:`loop.run_in_executor` メソッドを参照してください。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:130
msgid "Logging"
msgstr "ログ記録"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:132
msgid ""
"asyncio uses the :mod:`logging` module and all logging is performed via the "
"``\"asyncio\"`` logger."
msgstr ""
"asyncio は :mod:`logging` モジュールを利用し、 全てのログ記録は ``\"asyncio\"`` ロガーを通じて行われます。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:135
msgid ""
"The default log level is :py:data:`logging.INFO`, which can be easily "
"adjusted::"
msgstr "デフォルトのログレベルは :py:data:`logging.INFO` ですが、これは簡単に調節できます:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:144
msgid "Detect never-awaited coroutines"
msgstr "待ち受け処理を伴わないコルーチンの検出"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:146
msgid ""
"When a coroutine function is called, but not awaited (e.g. ``coro()`` "
"instead of ``await coro()``) or the coroutine is not scheduled with "
":meth:`asyncio.create_task`, asyncio will emit a :exc:`RuntimeWarning`::"
msgstr ""
"コルーチンが呼び出されただけで、待ち受け処理がない場合 (たとえば ``await coro()`` のかわりに ``coro()`` "
"と書いてしまった場合) 、またはコルーチンが :meth:`asyncio.create_task` を使わずにスケジュールされた場合、 asyncio"
" は :exc:`RuntimeWarning` 警告を送出します:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:161
#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:206
msgid "Output::"
msgstr "出力::"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:166
#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:222
msgid "Output in debug mode::"
msgstr "デバッグモードの出力::"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:179
msgid ""
"The usual fix is to either await the coroutine or call the "
":meth:`asyncio.create_task` function::"
msgstr ""
"通常の修正方法はコルーチンを待ち受ける (await) か、 :meth:`asyncio.create_task` 関数を呼び出すことです:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:187
msgid "Detect never-retrieved exceptions"
msgstr "回収されない例外の検出"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:189
msgid ""
"If a :meth:`Future.set_exception` is called but the Future object is never "
"awaited on, the exception would never be propagated to the user code.  In "
"this case, asyncio would emit a log message when the Future object is "
"garbage collected."
msgstr ""
"もし :meth:`Future.set_exception` メソッドが呼び出されても、その Future "
"オブジェクトを待ち受けていなければ、例外は決してユーザーコードまで伝播しません。この場合 asyncio は、 Future "
"オブジェクトがガベージコレクションの対象となったときにログメッセージを送出することがあります。"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:194
msgid "Example of an unhandled exception::"
msgstr "処理されない例外の例:"

#: /home/runner/work/docspush-transifex/docspush-transifex/cpython/Doc/library/asyncio-dev.rst:217
msgid ""
":ref:`Enable the debug mode <asyncio-debug-mode>` to get the traceback where"
" the task was created::"
msgstr ""
"タスクが生成された箇所を特定するには、 :ref:`デバッグモードを有効化して <asyncio-debug-mode>` "
"トレースバックを取得してください:"
